name: "Feature Request"
description: Create an issue for a new feature request
title: "Enhancement: <title>"
labels: ["enhancement"]
body:
  - type: textarea
    id: summary
    attributes:
      label: "Summary"
      description: Provide a brief summary of your feature request
      placeholder: Describe in a few lines your feature request
    validations:
      required: true
  - type: textarea
    id: basic_example
    attributes:
      label: "Basic Example"
      description: Indicate here some basic examples of your feature.
      placeholder: Provide some basic example of your feature request
    validations:
      required: false
  - type: textarea
    id: drawbacks
    attributes:
      label: "Drawbacks and Impact"
      description: What are the drawbacks or impacts of your feature request?
      placeholder: Describe any the drawbacks or impacts of your feature request
    validations:
      required: false
  - type: textarea
    id: unresolved_question
    attributes:
      label: "Unresolved questions"
      description: What, if any, unresolved questions do you have about your feature request?
      placeholder: Identify any unresolved issues.
    validations:
      required: false
  - type: checkboxes
    id: contribution-guidelines
    attributes:
      label: Contribution Guidelines
      description: By submitting this issue, you agree to follow Starlite's [Contribution Guidelines](https://starliteproject.dev/community/contribution-guide/index.html)
      options:
        - label: I agree to follow Starlite's Contribution Guidelines
          required: true
  - type: checkboxes
    id: code-of-conduct
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow Starlite's [Code of Conduct](https://github.com/starlite-api/.github/blob/main/CODE_OF_CONDUCT.md)
      options:
        - label: I agree to follow Starlite's Code of Conduct
          required: true
